"body {\n"
"    background-color: white;\n"
"    font-family: sans-serif;\n"
"}\n"
"\n"
"header {\n"
"   background-color: green;\n"
"\n"
"}\n"
"\n"
"#projectname {\n"
"    font-size: 80%;\n"
"    color: #666666;\n"
"}\n"
"#projectbrief {\n"
"    font-size: 50%;\n"
"    color: #666666;\n"
"}\n"
