"\n"
"<html>\n"
"<head>\n"
"<meta http-equiv=\"Content-Type\" content=\"text/xhtml;charset=UTF-8\"/>\n"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\"/>\n"
"<meta name=\"generator\" content=\"Doxygen $doxygenversion\"/>\n"
"<!--BEGIN PROJECT_NAME--><title>$projectname: $title</title><!--END PROJECT_NAME-->\n"
"<!--BEGIN !PROJECT_NAME--><title>$title</title><!--END !PROJECT_NAME-->\n"
"<deadlink href=\"$relpath^tabs.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"
"<script type=\"text/javascript\" src=\"$relpath^jquery.js\"></script>\n"
"<script type=\"text/javascript\" src=\"$relpath^dynsections.js\"></script>\n"
"$treeview\n"
"$search\n"
"$mathjax\n"
"<link href=\"$relpath^$stylesheet\" rel=\"stylesheet\" type=\"text/css\" />\n"
"$extrastylesheet\n"
"</head>\n"
"\n"
"<body>\n"
"<div id=\"main_container\"></div>\n"
"<header>\n"
"    <div id=\"projectlogo\"><img alt=\"Logo\" src=\"$relpath^$projectlogo\"/></td>\n"
"    <h1 id=\"projectname\">$projectname &#160;<span id=\"projectnumber\">$projectnumber</span></h1>\n"
"    <h2 id=\"projectbrief\">$projectbrief</h1>\n"
"</header>\n"
